services:
  apisix:
    image: 'apache/apisix:3.12.0-debian'
    restart: always
    volumes:
      - ./apisix_conf.yml:/usr/local/apisix/conf/config.yaml:ro
    depends_on:
      - etcd
    networks:
      - apisix

  etcd:
    image: bitnami/etcd:3.5
    restart: always
    volumes:
      - etcd_data:/bitnami/etcd
    environment:
      ETCD_ENABLE_V2: 'true'
      ALLOW_NONE_AUTHENTICATION: 'yes'
      ETCD_ADVERTISE_CLIENT_URLS: 'http://etcd:2379'
      ETCD_LISTEN_CLIENT_URLS: 'http://0.0.0.0:2379'
    networks:
      - apisix

networks:
  apisix:
    driver: bridge

volumes:
  etcd_data:
