name: Frontend e2e test

on:
  push:
    branches:
      - main
      - 'dev/*'
  pull_request:
    types: [labeled, synchronize]
    branches:
      - main
      - dev/**
      - '**test/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    if: ${{ contains(github.event.pull_request.labels.*.name, 'e2e-test') }}
    timeout-minutes: 40
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Get PR Labels
        id: get-labels
        uses: actions/github-script@v6
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            core.setOutput("labels", labels.join(","));
      - name: Set image label as environment variable
        run: |
          export LABELS=${{ steps.get-labels.outputs.labels }}
          echo "LABELS=${LABELS}" >> $GITHUB_ENV
        shell: bash

      - name: Install dependencies
        run: corepack enable pnpm && pnpm install

      - name: Code and type checking
        run: pnpm lint

      - name: Install Playwright Browsers
        run: |
          pnpm exec playwright install --with-deps

      - name: Run e2e tests
        run: |
          pnpm e2e --verbose

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: test-results
          path: apps/site-e2e/test-results/
          retention-days: 7

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 7

      - name: Show Port Forward Log
        if: failure()
        run: |
          cat /tmp/portforward-*

      - name: Print Components Logs
        if: failure()
        run: |
          docker ps --format '{{.Names}}' | xargs -I{} bash -c "echo ================= {} ==================== &&  docker logs {} && echo ================= {} ===================="
